In [1]:
import tensorflow as tf
from tensorflow import keras
import cv2
import numpy as np
import os
from tensorflow import keras

In [2]:
IMAGE_SIZE = (100,100)
def load_images():
    image = []
    label = []
    image_path = []
    TRAIN_FOLDER_PATH = "D:/Programming/OPSI/images/train"#"C:/Users/pc/Documents/pythonProjects/OPSI/images/train" #ada sebanyak 3421 image
    TEST_FOLDER_PATH = "D:/Programming/OPSI/images/test"#"C:/Users/pc/Documents/pythonProjects/OPSI/images/test" #ada sebanyak 1871 image, total ada 5292 images
    for folder_name in os.listdir(TRAIN_FOLDER_PATH):
        for filename in os.listdir(os.path.join(TRAIN_FOLDER_PATH,folder_name)):
            print(filename)
            subfolder_path = os.path.join(folder_name,filename)
            img = cv2.imread(os.path.join(TRAIN_FOLDER_PATH,subfolder_path))
            img = cv2.resize(img,IMAGE_SIZE)
            image.append(img)
            label.append(folder_name)
            image_path.append(os.path.join(TRAIN_FOLDER_PATH,subfolder_path))

    for folder_name in os.listdir(TEST_FOLDER_PATH):
        for filename in os.listdir(os.path.join(TEST_FOLDER_PATH,folder_name)):
            print(filename)
            subfolder_path = os.path.join(folder_name,filename)
            img = cv2.imread(os.path.join(TEST_FOLDER_PATH,subfolder_path))
            img = cv2.resize(img,IMAGE_SIZE)
            image.append(img)
            label.append(folder_name)
            image_path.append(os.path.join(TEST_FOLDER_PATH,subfolder_path))
    image = np.array(image)
    return image,label, image_path

In [3]:
image,label, image_path = load_images()

adenocarcinoma_left lower lobe T2 N0 M0 Ib (1).png
adenocarcinoma_left lower lobe T2 N0 M0 Ib (10).png
adenocarcinoma_left lower lobe T2 N0 M0 Ib (100).png
adenocarcinoma_left lower lobe T2 N0 M0 Ib (101).png
adenocarcinoma_left lower lobe T2 N0 M0 Ib (102).png
adenocarcinoma_left lower lobe T2 N0 M0 Ib (103).png
adenocarcinoma_left lower lobe T2 N0 M0 Ib (104).png
adenocarcinoma_left lower lobe T2 N0 M0 Ib (105).png
adenocarcinoma_left lower lobe T2 N0 M0 Ib (106).png
adenocarcinoma_left lower lobe T2 N0 M0 Ib (107).png
adenocarcinoma_left lower lobe T2 N0 M0 Ib (108) - Copy.png
adenocarcinoma_left lower lobe T2 N0 M0 Ib (108).png
adenocarcinoma_left lower lobe T2 N0 M0 Ib (109) - Copy.png
adenocarcinoma_left lower lobe T2 N0 M0 Ib (109).png
adenocarcinoma_left lower lobe T2 N0 M0 Ib (11).png
adenocarcinoma_left lower lobe T2 N0 M0 Ib (110) - Copy.png
adenocarcinoma_left lower lobe T2 N0 M0 Ib (110).png
adenocarcinoma_left lower lobe T2 N0 M0 Ib (111) - Copy.png
adenocarcinoma_left lo

In [4]:
print(len(image)) #banyaknya data gambar untuk train session
print(label)
print(len(label))
image.shape

7871
['Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adenocarcinoma (Ganas)', 'Adeno

(7871, 100, 100, 3)

In [5]:
# i = 5000
# print(label[i])
# cv2.imshow('image',image[i])
# cv2.waitKey(0)

In [6]:
from sklearn.preprocessing import OneHotEncoder
label_encoder = OneHotEncoder()
new_label = np.reshape(label,(-1,1))
new_label = label_encoder.fit_transform(new_label).toarray()

In [7]:
print(new_label)
print(len(new_label [0]))
print(new_label .shape)
# new_label = np.resize(new_label,(5292,10))
print(new_label.shape)
new_label[0]

[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
6
(7871, 6)
(7871, 6)


array([1., 0., 0., 0., 0., 0.])

In [8]:
from keras.preprocessing.image import ImageDataGenerator
augmentation = ImageDataGenerator(
    zoom_range=0.2,
    shear_range=0.2,
    horizontal_flip=True
)

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(image,new_label,test_size=0.2,random_state=3)

In [10]:
# model_xception = keras.applications.xception.Xception(weights='imagenet',include_top=False,input_tensor=keras.layers.Input(shape=(100,100,3)))

# for layer in model_xception.layers:
#     layer.trainable = False
# print(model_xception.summary())

In [11]:
# model_lenet5 = keras.Sequential()
# model_lenet5.add(keras.layers.Conv2D(filters=32, kernel_size=(5, 5), activation='relu', input_shape=(100,100, 3)))
# model_lenet5.add(keras.layers.AveragePooling2D(pool_size=(2, 2), strides=2))
# model_lenet5.add(keras.layers.Conv2D(filters=64, kernel_size=(5, 5), activation='relu'))
# model_lenet5.add(keras.layers.AveragePooling2D(pool_size=(2, 2), strides=2))
# model_lenet5.add(keras.layers.Flatten())

# model_lenet5.add(keras.layers.Dense(units=120, activation='relu'))
# model_lenet5.add(keras.layers.Dense(units=84, activation='relu'))
# model_lenet5.add(keras.layers.Dense(units=6, activation='softmax'))
# model_lenet5.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
# model_lenet5.summary()

In [12]:
resnet50 = keras.applications.resnet.ResNet50(weights='imagenet',include_top=False,input_tensor=keras.layers.Input(shape=(100,100,3)))

for layer in resnet50.layers:
    layer.trainable = False
    
print(resnet50.summary())

Model: "resnet50"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 100, 100, 3  0           []                               
                                )]                                                                
                                                                                                  
 conv1_pad (ZeroPadding2D)      (None, 106, 106, 3)  0           ['input_1[0][0]']                
                                                                                                  
 conv1_conv (Conv2D)            (None, 50, 50, 64)   9472        ['conv1_pad[0][0]']              
                                                                                                  
 conv1_bn (BatchNormalization)  (None, 50, 50, 64)   256         ['conv1_conv[0][0]']      

In [13]:
model_resnet50 = keras.Sequential()
model_resnet50.add(resnet50)
model_resnet50.add(keras.layers.Flatten())

model_resnet50.add(keras.layers.Dense(units=6, activation='softmax'))

model_resnet50.compile(optimizer=keras.optimizers.Adam(learning_rate=0.001), loss='categorical_crossentropy', metrics=['accuracy'])
model_resnet50.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 resnet50 (Functional)       (None, 4, 4, 2048)        23587712  
                                                                 
 flatten (Flatten)           (None, 32768)             0         
                                                                 
 dense (Dense)               (None, 6)                 196614    
                                                                 
Total params: 23,784,326
Trainable params: 196,614
Non-trainable params: 23,587,712
_________________________________________________________________


In [14]:
model_resnet50.fit(augmentation.flow(x_train, y_train, batch_size=32),validation_data=(x_test,y_test),epochs=10)

Epoch 1/10
197/197 [==============================] - 102s 507ms/step - loss: 1.5971 - accuracy: 0.7541 - val_loss: 1.1388 - val_accuracy: 0.8127
Epoch 2/10
197/197 [==============================] - 99s 502ms/step - loss: 1.0917 - accuracy: 0.8389 - val_loss: 0.5973 - val_accuracy: 0.8863
Epoch 3/10
197/197 [==============================] - 97s 493ms/step - loss: 0.7580 - accuracy: 0.8855 - val_loss: 0.7358 - val_accuracy: 0.8762
Epoch 4/10
197/197 [==============================] - 100s 509ms/step - loss: 0.7298 - accuracy: 0.8976 - val_loss: 1.1590 - val_accuracy: 0.8698
Epoch 5/10
197/197 [==============================] - 102s 519ms/step - loss: 0.5863 - accuracy: 0.9160 - val_loss: 1.2100 - val_accuracy: 0.8635
Epoch 6/10
197/197 [==============================] - 102s 516ms/step - loss: 0.4414 - accuracy: 0.9366 - val_loss: 0.1904 - val_accuracy: 0.9676
Epoch 7/10
197/197 [==============================] - 100s 508ms/step - loss: 0.5256 - accuracy: 0.9298 - val_loss: 0.3913 - v

In [15]:
model_resnet50.evaluate(x_test,y_test)

50/50 [==============================] - 20s 407ms/step - loss: 0.7622 - accuracy: 0.9060


[0.762157142162323, 0.9060317277908325]

In [16]:
model_resnet50.save('resnet50augmented.h5')

In [18]:
prediction = model_resnet50.predict(x_test)
prediction

50/50 [==============================] - 22s 436ms/step


array([[6.5684726e-32, 2.1954229e-12, 4.1867319e-05, 9.9995816e-01,
        1.1923244e-20, 6.2196838e-26],
       [8.3112258e-30, 3.2213830e-31, 8.3583923e-19, 1.0000000e+00,
        3.2462343e-27, 0.0000000e+00],
       [0.0000000e+00, 8.9429527e-35, 1.0000000e+00, 6.5437691e-15,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [7.3802541e-26, 1.0000000e+00, 5.2172598e-14, 1.9367061e-21,
        2.5964049e-31, 1.1564882e-33],
       [2.0774093e-29, 2.5366120e-20, 1.0000000e+00, 1.3252537e-13,
        1.7556134e-34, 7.6343290e-35],
       [7.3320126e-12, 8.6179154e-22, 4.2911857e-28, 3.3624287e-19,
        2.0478856e-31, 1.0000000e+00]], dtype=float32)

In [19]:
jenis_kanker = ["Adenocarcinoma","Kanker Ganas","Kanker Jinak", "Sehat", "Sel Besar Karsinoma", "Sel Besar Skuamous"]
banyak_kesalahan = 0
for i in range(len(prediction)):
    if jenis_kanker[np.argmax(prediction[i])] != jenis_kanker[np.argmax(y_test[i])]:
        banyak_kesalahan += 1
        print("data ke :",  i+1)
        print("Prediction : " + jenis_kanker[np.argmax(prediction[i])])
        print("Kunci Jawaban: ",jenis_kanker[np.argmax(y_test[i])])
        print()
print(banyak_kesalahan)

data ke : 6
Prediction : Kanker Jinak
Kunci Jawaban:  Sehat

data ke : 18
Prediction : Kanker Jinak
Kunci Jawaban:  Sehat

data ke : 19
Prediction : Kanker Jinak
Kunci Jawaban:  Sehat

data ke : 30
Prediction : Adenocarcinoma
Kunci Jawaban:  Sel Besar Skuamous

data ke : 43
Prediction : Kanker Jinak
Kunci Jawaban:  Sehat

data ke : 47
Prediction : Kanker Jinak
Kunci Jawaban:  Sehat

data ke : 60
Prediction : Kanker Jinak
Kunci Jawaban:  Sehat

data ke : 61
Prediction : Adenocarcinoma
Kunci Jawaban:  Sel Besar Karsinoma

data ke : 66
Prediction : Kanker Jinak
Kunci Jawaban:  Sehat

data ke : 74
Prediction : Kanker Jinak
Kunci Jawaban:  Sehat

data ke : 84
Prediction : Kanker Jinak
Kunci Jawaban:  Sehat

data ke : 93
Prediction : Adenocarcinoma
Kunci Jawaban:  Sel Besar Skuamous

data ke : 96
Prediction : Kanker Jinak
Kunci Jawaban:  Sehat

data ke : 107
Prediction : Adenocarcinoma
Kunci Jawaban:  Sel Besar Karsinoma

data ke : 121
Prediction : Adenocarcinoma
Kunci Jawaban:  Sel Besar Ka

In [20]:
print(len(y_test))
banyak_kesalahan

1575


148

In [21]:
akurasi_training = lenet_xception.evaluate(x_train,y_train)[1]
akurasi_testing = lenet_xception.evaluate(x_test,y_test)[1]

NameError: name 'lenet_xception' is not defined

In [ ]:
print("Akurasi training session :",akurasi_training)
print("Akurasi testing session :",akurasi_testing)